# Site settings
title:       A Data Blog
email:       prockley1@gmail.com
author:      Paul Rockley
description: "A data blog about everything and anything. Not sure where it's headed as yet."

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url:     "http://www.prockley.eu"
# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl:      "http://www.prockley.eu"

# Google analytics
google_analytics: UA-57994674-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: true
github_username: prockley
twitter_username: prockley
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true
