# Site settings
title:       Pixyll
email:       your_email@example.com
author:      Paul Rockley
description: "A data blog about everything and anything. No editiorial limits as yet."

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url:     "http://prockley.github.io"
# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl:      "http://prockley.github.io"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  true

# Social icons
show_social_icons: true
github_username: prockley
twitter_username:
google_plus_id:
linkedin_username: example
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true
